#+TITLE: Lexical Token
#+PROPERTY: header-args    :comments both :tangle ../src/LexicalToken.js

To facilitate lexing, let's make a class of helpers to construct lexical tokens with the right shape

First a class for a simple token. I hate the =new= keyword, so make a simple factory function.

* Token Factories
#+begin_src js
const SimpleToken = (...args) => new _SimpleToken(...args);

class _SimpleToken {
    constructor(name, type, original) {
        this.type = type;
        this.name = name;
        this.original = original;
    }

    is(token) {
        return this.name == token.name;
    }

    finalize() { /* noop */ return this; }
}
#+end_src

Now for tokens of multiple characters, the lexer only receives one letter at a time, so further characters will be added to it.

#+begin_src js
const ExpandableToken = (...args) => new _ExpandableToken(...args);

class _ExpandableToken extends _SimpleToken {
    constructor(...args) {
        super(...args);
    }

    push(char) {
        this.original += char;
    }
    
    finalize() { /* noop */ return this; }
}
#+end_src

Now we make specific factories for all identifier tokens, who extract the text of the identifier from the syntax that created it, e.g. =add!= is a CallIdentifier but the identifier is just "add".

The simplest is a value identifier, where the identifier is the original exactly. This seems like a useless addition if they're just the same, but if all the identifiers work the same way it makes other code much simpler.

#+begin_src js
const ValueIdentifierToken = (...args) => new _ValueIdentifierToken(...args);

class _ValueIdentifierToken extends _ExpandableToken {
    finalize() { this.identifier = this.original; return this; }
}
#+end_src

#+begin_src js
const AddressIdentifierToken = (...args) => new _AddressIdentifierToken(...args);

class _AddressIdentifierToken extends _ExpandableToken {
    finalize() { this.identifier = this.original.replace("@", ""); return this; }
}
#+end_src

#+begin_src js
const CallIdentifierToken = (...args) => new _CallIdentifierToken(...args);

class _CallIdentifierToken extends _ExpandableToken {
    finalize() { this.identifier = this.original.replace("!", ""); return this; }
}
#+end_src

#+begin_src js
const LabelIdentifierToken = (...args) => new _LabelIdentifierToken(...args);

class _LabelIdentifierToken extends _ExpandableToken {
    finalize() { this.identifier = this.original.replace(":", ""); return this; }
}
#+end_src

* Token
A data structure mapping token names to information about it.

#+begin_src js
export const Token = {};
Token.ValueIdentifier = {
    event: "VALUE_IDENTIFIER",
    factory: ValueIdentifierToken,
};
Token.AddressIdentifier = {
    event: "ADDRESS_IDENTIFIER",
    factory: AddressIdentifierToken,
};
Token.CallIdentifier = {
    event: "CALL_IDENTIFIER",
    factory: CallIdentifierToken,
};
Token.LabelIdentifier = {
    event: "LABEL_IDENTIFIER",
    factory: LabelIdentifierToken,
};
Token.Number = {
    event: "NUMBER",
    factory: ExpandableToken,
};
Token.String = {
    event: "STRING",
    factory: ExpandableToken,
};
Token.Blank = {
    event: "BLANK",
    factory: SimpleToken,
    literal: "_"
};
Token.Comma = {
    event: "COMMA",
    factory: SimpleToken,
    literal: ","
};
Token.OpenTape = {
    event: "OPEN_TAPE",
    factory: SimpleToken,
    literal: "["
};
Token.CloseTape = {
    event: "CLOSE_TAPE",
    factory: SimpleToken,
    literal: "]"
};
Token.OpenParams = {
    event: "OPEN_PARAMS",
    factory: SimpleToken,
    literal: "("
};
Token.CloseParams = {
    event: "CLOSE_PARAMS",
    factory: SimpleToken,
    literal: ")"
};
Token.OpenInlineTape = {
    event: "OPEN_INLINE_TAPE",
    factory: SimpleToken,
    literal: "{"
};
Token.CloseInlineTape = {
    event: "CLOSE_INLINE_TAPE",
    factory: SimpleToken,
    literal: "}"
};
#+end_src

Now construct the factories and add other automatic information.

#+begin_src js
Object.entries(Token).forEach(([name, value]) => {
    value.name = name;
    
    // All complex factories are called the same way
    if (value.factory !== SimpleToken) {
        value.create = (char) => value.factory(name, value.event, char);
    }
    else if (value.factory == SimpleToken) {
        value.create = () => SimpleToken(name, value.event, value.literal);
    }
    else throw new Error(`Token ${name} has no factory`)
})
#+end_src
